# Generated by Django 5.1.7 on 2025-04-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('rfc', models.CharField(max_length=100)),
                ('curp', models.CharField(max_length=100)),
                ('regimen', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('colonia', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('cp', models.CharField(max_length=10)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(max_length=20)),
                ('ocupacion', models.CharField(max_length=100)),
                ('escolaridad', models.CharField(max_length=100)),
                ('telefono_emergencia', models.CharField(max_length=15)),
                ('parentesco', models.CharField(max_length=50)),
                ('nombre_emergencia', models.CharField(max_length=100)),
                ('apellido_emergencia', models.CharField(max_length=100)),
                ('nombre_referencia', models.CharField(max_length=100)),
                ('apellido_referencia', models.CharField(max_length=100)),
                ('telefono_referencia', models.CharField(max_length=15)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('antiguedad', models.IntegerField()),
                ('sueldo_empresa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('telefono_empresa', models.CharField(max_length=15)),
                ('direccion_empresa', models.CharField(max_length=100)),
                ('cp_empresa', models.CharField(max_length=10)),
            ],
        ),
    ]
