# Generated by Django 5.1.7 on 2025-04-03 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='registro.estado')),
            ],
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='registro.pais'),
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('mujer', 'Mujer'), ('hombre', 'Hombre')], default='mujer', max_length=10)),
                ('estado_fisico', models.CharField(choices=[('vivo', 'Vivo'), ('muerto', 'Muerto')], default='vivo', max_length=10)),
                ('rfc', models.CharField(blank=True, max_length=9, null=True)),
                ('curp', models.CharField(blank=True, max_length=100, null=True)),
                ('regimen', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('cp', models.CharField(blank=True, max_length=10, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=20, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('escolaridad', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=15, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_emergencia', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_emergencia', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_referencia', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('puesto', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('antiguedad', models.IntegerField(blank=True, null=True)),
                ('sueldo_empresa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('telefono_empresa', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('cp_empresa', models.CharField(blank=True, max_length=10, null=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.ciudad')),
            ],
        ),
    ]
