# Generated by Django 5.1.7 on 2025-04-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_registro_mascotas_alter_registro_antiguedad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='rfc',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
