# Generated by Django 5.1.7 on 2025-04-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alter_registro_estado_civil'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='contrato',
            field=models.FileField(blank=True, null=True, upload_to='contratos/'),
        ),
    ]
