# Generated by Django 5.1.7 on 2025-06-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_registro_usuario_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
