# Generated by Django 5.1.7 on 2025-06-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_alter_registro_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
