# Generated by Django 5.1.7 on 2025-07-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_alter_registro_fecha_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'País'},
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='telefono',
            new_name='telefono_casa',
        ),
        migrations.AddField(
            model_name='registro',
            name='alergias_descrp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='enfermedad_descrp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='telefono_celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='tipo_sangre',
            field=models.CharField(choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('o+', 'O+'), ('o-', 'O-')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='registro',
            name='regimen',
            field=models.CharField(blank=True, choices=[('sueldos_salarios', 'Sueldos y Salarios'), ('honorarios', 'Honorarios'), ('arrendamiento', 'Arrendamiento'), ('actividades_empresariales', 'Actividades Empresariales'), ('rif', 'RIF'), ('incorporacion_fiscal', 'Incorporación Fiscal')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='alergias',
            field=models.ManyToManyField(to='registro.alergia'),
        ),
        migrations.AddField(
            model_name='registro',
            name='enfermedad',
            field=models.ManyToManyField(to='registro.enfermedade'),
        ),
    ]
